version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: qa_user
      POSTGRES_PASSWORD: qa_pass123
      POSTGRES_DB: logistics
    volumes:
      - ./app/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"   # 5434 — чтобы не конфликтовать с другими БД
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U qa_user -d logistics"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./app
    environment:
      DATABASE_URL: postgresql://qa_user:qa_pass123@db:5432/logistics
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
